assignment8-QLMS/config/routes.rb
Rails.application.routes.draw do
  resources :ql_muon_saches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

assignment8-QLMS/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

assignment8-QLMS/app/models/ql_muon_sach.rb
class QlMuonSach < ApplicationRecord
end

assignment8-QLMS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

assignment8-QLMS/app/controllers/ql_muon_saches_controller.rb
class QlMuonSachesController < ApplicationController
  before_action :set_ql_muon_sach, only: %i[ show edit update destroy ]

  # GET /ql_muon_saches or /ql_muon_saches.json
  def index
    @ql_muon_saches = QlMuonSach.all
  end

  # GET /ql_muon_saches/1 or /ql_muon_saches/1.json
  def show
  end

  # GET /ql_muon_saches/new
  def new
    @ql_muon_sach = QlMuonSach.new
  end

  # GET /ql_muon_saches/1/edit
  def edit
  end

  # POST /ql_muon_saches or /ql_muon_saches.json
  def create
    @ql_muon_sach = QlMuonSach.new(ql_muon_sach_params)

    respond_to do |format|
      if @ql_muon_sach.save
        format.html { redirect_to ql_muon_sach_url(@ql_muon_sach), notice: "Ql muon sach was successfully created." }
        format.json { render :show, status: :created, location: @ql_muon_sach }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ql_muon_sach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ql_muon_saches/1 or /ql_muon_saches/1.json
  def update
    respond_to do |format|
      if @ql_muon_sach.update(ql_muon_sach_params)
        format.html { redirect_to ql_muon_sach_url(@ql_muon_sach), notice: "Ql muon sach was successfully updated." }
        format.json { render :show, status: :ok, location: @ql_muon_sach }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ql_muon_sach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ql_muon_saches/1 or /ql_muon_saches/1.json
  def destroy
    @ql_muon_sach.destroy

    respond_to do |format|
      format.html { redirect_to ql_muon_saches_url, notice: "Ql muon sach was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ql_muon_sach
      @ql_muon_sach = QlMuonSach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ql_muon_sach_params
      params.require(:ql_muon_sach).permit(:tt, :stt, :maHS, :hoVaTen, :lop, :maSach, :tenSach, :tenTacGia, :tuSach, :soBM, :ngayMuon, :ngayTra, :soNgay, :ghiChu)
    end
end

assignment8-QLMS/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment8-QLMS/app/helpers/ql_muon_saches_helper.rb
module QlMuonSachesHelper
end

assignment8-QLMS/app/views/layouts/_header.html.erb
<div class = "container-fluid">
<div class="row">
    <div class="col-4 text-center mb-4" style="color: green">
      <h5>THƯ VIỆN</h5>
      <h5>TRƯỜNG TIỂU HỌC PHONG THẠNH TÂY A</h5>
    </div>
</div>
<div class="row">
    <div class="col-12">
      <h2 class="text-uppercase align-items-center d-flex justify-content-center" style="color: red">
        <%= link_to image_tag("logo-sach.png", alt: "Logo", style:"width: 35px; height: 35px"), 'http://rubyonrails.org/', style: "margin-right: 20px" %>
        Quản lý cho học sinh mượn sách
      </h2>
</div>

assignment8-QLMS/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quản lý mượn sách</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <br>
    <%= render "/layouts/header" %>
    <br>
    
    <div class="container-fluid">
      <%= yield %>
      <br/>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

assignment8-QLMS/app/views/ql_muon_saches/_form.html.erb
<%= form_with(model: ql_muon_sach) do |form| %>
  <% if ql_muon_sach.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ql_muon_sach.errors.count, "error") %> prohibited this ql_muon_sach from being saved:</h2>

      <ul>
        <% ql_muon_sach.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tt, style: "display: block" %>
    <%= form.text_field :tt %>
  </div>

  <div>
    <%= form.label :stt, style: "display: block" %>
    <%= form.number_field :stt %>
  </div>

  <div>
    <%= form.label :maHS, style: "display: block" %>
    <%= form.text_field :maHS %>
  </div>

  <div>
    <%= form.label :hoVaTen, style: "display: block" %>
    <%= form.text_field :hoVaTen %>
  </div>

  <div>
    <%= form.label :lop, style: "display: block" %>
    <%= form.text_field :lop %>
  </div>

  <div>
    <%= form.label :maSach, style: "display: block" %>
    <%= form.text_field :maSach %>
  </div>

  <div>
    <%= form.label :tenSach, style: "display: block" %>
    <%= form.text_field :tenSach %>
  </div>

  <div>
    <%= form.label :tenTacGia, style: "display: block" %>
    <%= form.text_field :tenTacGia %>
  </div>

  <div>
    <%= form.label :tuSach, style: "display: block" %>
    <%= form.text_field :tuSach %>
  </div>

  <div>
    <%= form.label :soBM, style: "display: block" %>
    <%= form.number_field :soBM %>
  </div>

  <div>
    <%= form.label :ngayMuon, style: "display: block" %>
    <%= form.date_field :ngayMuon %>
  </div>

  <div>
    <%= form.label :ngayTra, style: "display: block" %>
    <%= form.date_field :ngayTra %>
  </div>

  <div>
    <%= form.label :soNgay, style: "display: block" %>
    <%= form.number_field :soNgay %>
  </div>

  <div>
    <%= form.label :ghiChu, style: "display: block" %>
    <%= form.text_field :ghiChu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

assignment8-QLMS/app/views/ql_muon_saches/_ql_muon_sach.html.erb
<div id="<%= dom_id ql_muon_sach %>">
  <p>
    <strong>Tt:</strong>
    <%= ql_muon_sach.tt %>
  </p>

  <p>
    <strong>Stt:</strong>
    <%= ql_muon_sach.stt %>
  </p>

  <p>
    <strong>Mahs:</strong>
    <%= ql_muon_sach.maHS %>
  </p>

  <p>
    <strong>Hovaten:</strong>
    <%= ql_muon_sach.hoVaTen %>
  </p>

  <p>
    <strong>Lop:</strong>
    <%= ql_muon_sach.lop %>
  </p>

  <p>
    <strong>Masach:</strong>
    <%= ql_muon_sach.maSach %>
  </p>

  <p>
    <strong>Tensach:</strong>
    <%= ql_muon_sach.tenSach %>
  </p>

  <p>
    <strong>Tentacgia:</strong>
    <%= ql_muon_sach.tenTacGia %>
  </p>

  <p>
    <strong>Tusach:</strong>
    <%= ql_muon_sach.tuSach %>
  </p>

  <p>
    <strong>Sobm:</strong>
    <%= ql_muon_sach.soBM %>
  </p>

  <p>
    <strong>Ngaymuon:</strong>
    <%= ql_muon_sach.ngayMuon %>
  </p>

  <p>
    <strong>Ngaytra:</strong>
    <%= ql_muon_sach.ngayTra %>
  </p>

  <p>
    <strong>Songay:</strong>
    <%= ql_muon_sach.soNgay %>
  </p>

  <p>
    <strong>Ghichu:</strong>
    <%= ql_muon_sach.ghiChu %>
  </p>

</div>

assignment8-QLMS/app/views/ql_muon_saches/edit.html.erb
<h1>Editing ql muon sach</h1>

<%= render "form", ql_muon_sach: @ql_muon_sach %>

<br>

<div>
  <%= link_to "Show this ql muon sach", @ql_muon_sach %> |
  <%= link_to "Back to ql muon saches", ql_muon_saches_path %>
</div>

assignment8-QLMS/app/views/ql_muon_saches/index.html.erb
<br/>
<div class = "container-fluid">
<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>TT</th>
        <th>STT</th>
        <th>Mã HS</th>
        <th>Họ và tên</th>
        <th>Lớp</th>
        <th>Mã sách</th>
        <th>Tên sách</th>
        <th>Tên tác giả</th>
        <th>Tủ sách</th>
        <th>Số BM</th>
        <th>Ngày mượn</th>
        <th>Ngày trả</th>
        <th>Số ngày</th>
        <th>Ghi chú</th>
      </tr>
    </thead>

    <tbody>
      <% @ql_muon_saches.each do |ql_muon_sach_118| %>
        <tr>
          <td><%= ql_muon_sach_118.tt %></td>
          <td><%= ql_muon_sach_118.id %></td>
          <td><%= ql_muon_sach_118.maHS %></td>
          <td><%= ql_muon_sach_118.hoVaTen %></td>
          <td><%= ql_muon_sach_118.lop %></td>
          <td><%= ql_muon_sach_118.maSach %></td>
          <td><%= ql_muon_sach_118.tenSach %></td>
          <td><%= ql_muon_sach_118.tenTacGia %></td>
          <td><%= ql_muon_sach_118.tuSach %></td>
          <td><%= ql_muon_sach_118.soBM %></td>
          <td><%= ql_muon_sach_118.ngayMuon %></td>
          <td><%= ql_muon_sach_118.ngayTra %></td>
          <td><%= ql_muon_sach_118.soNgay %></td>
          <td><%= ql_muon_sach_118.ghiChu %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br/>
</div>

assignment8-QLMS/app/views/ql_muon_saches/new.html.erb
<h1>New ql muon sach</h1>

<%= render "form", ql_muon_sach: @ql_muon_sach %>

<br>

<div>
  <%= link_to "Back to ql muon saches", ql_muon_saches_path %>
</div>

assignment8-QLMS/app/views/ql_muon_saches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ql_muon_sach %>

<div>
  <%= link_to "Edit this ql muon sach", edit_ql_muon_sach_path(@ql_muon_sach) %> |
  <%= link_to "Back to ql muon saches", ql_muon_saches_path %>

  <%= button_to "Destroy this ql muon sach", @ql_muon_sach, method: :delete %>
</div>